### PR TITLE
eslint --fix

### PR DESCRIPTION
**Pull request by marcus-oscarsson**
Hello everybody

I hope you had a nice trip back to Sweden, It was wonderful to see you all !.

So I started to perform the eslint fix, I have already managed to get rid of alot of errors but there
is still plenty remaining. I have tested what Ive done here and it seem to work like before. Ill stop here for the moment to give you the possibility to try it out before I continue.

The --fix option is a little bit unstable and stops the fixing sometimes but continues the error report, so it looks like it did what it could to fix the errors. I don't know exactly why but it could be that some exception is raised and the error fixing is somehow aborted but the reporting is still done. Regardless of the cause, the result is as that it really looks like eslint fixed all the errors it could fix. 

Sometimes just running it twice solves some more issues, fixing some manual and then running again sometimes also works. Running eslint on individual files ore sub directories work much better than the entire directory structure.

We still have some (not so few actually :) ) errors to fix but we also got rid of plenty. You can perhaps give the eslint --fix a try on the files that you are working on and see if it does any difference.

Thanks,
Marcus

### CODE REVIEW

**Comment by mguijarr** [comment]
I just had to rebase this one to make it "mergeable" again, because the master branch changed 
as I accepted a PR from Frederik. 

Potential mistakes are mine.

Could someone test it quickly and see if we can merge it as soon as possible ?
As linting changes a lot of code, it's painful if all repositories are not in sync.

**Comment by mguijarr** [comment]
Any news on this one ?
I am worried about code divergence.

**Comment by bolmsten** [comment]
I am having problems to get this to run out of the box: 

First I got problems with some linting rules being duplicated and now I get a runtime error of:

main.js:40239 Uncaught Error: Cannot find module "../components/SampleView/SampleImage"

**Comment by bolmsten** [comment]
Are you able to run this on a clean install?

**Comment by mguijarr** [comment]
Thanks for the test Frederik.
I am sorry I did a bad merge after I accepted your last PR.
Now the problem is fixed - I think the code is ok, it works for me at least.
Can you please do your tests and if you agree we can merge this one.
I know it's painful because it's changing a lot of files etc. but it's the price to pay for having a cleaner code base.
Although there are still dozens of errors ! :(

**Comment by amilan** [comment]
UPPPSSSS!!!! Sorry, I mixed PRs! This one has been tested and it's OK to be merged it, but unfortunately I merged the wrong PR in the master branch and now there are some conflicts in this one. 
Is it possible for you to get those changes from Master, merged into this branch and add them to this pull request?
Sorry for the extra work due to my incompetence.
If not, I can also get both branches and merge them, but it will need to wait until tomorrow.

Sorry again.

**Comment by mguijarr** [comment]
It's fixed, go ahead :)

**Comment by amilan** [comment]
THANKS!
